# Generated by Django 2.1.7 on 2021-02-27 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210228_0605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='personality',
        ),
        migrations.AddField(
            model_name='profile',
            name='personality',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
